image: cati/brainvisa-opensource:ubuntu-16.04-bug_fix

before_script:
  - sudo apt-get -qq install --no-install-recommends libgsl0-dev

build:
  script:
    - cmake -DCMAKE_PREFIX_PATH=$HOME/build -DCMAKE_BUILD_TYPE=Release .
    - make
